version: '2.3'
services:
  hubs:
    build: ../hubs
    image: mozzila-hubs
    restart: always
    ports:
      - '8080:8080'
    environment:
      - JANUS_SERVER=wss://janus
      - DEV_RETICULUM_SERVER=reticulum
    # network_mode: "host"
  spoke:
    build: ../Spoke
    image: spoke
    restart: always
    ports:
      - '8081:80'
    environment:
      - JANUS_SERVER=wss://janus
      - DEV_RETICULUM_SERVER=reticulum
    # network_mode: "host"

  reticulum:
    build: ../reticulum
    image: mozzila-reticulum
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - db
    # network_mode: "host"

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    # network_mode: "host"

  janus:
    build: janus
    image: janus
    restart: always
    # network_mode: "host"

  # caddy:
  #   image: yukimochi/container-caddy
  #   restart: always
  #   network_mode: "host"
  #   volumes:
  #     - ./caddy/cert:/cert
  #     - ./caddy/conf:/etc/caddy
  #     - ./caddy/logs:/var/log/caddy
