version: '2.3'
services:
  hubs:
    build: hubs
    image: yukimochi/mr-hubs
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - JANUS_SERVER=wss://janus.vr.yukimochi.io
      - DEV_RETICULUM_SERVER=reticulum.vr.yukimochi.io

  reticulum:
    build: reticulum
    image: yukimochi/mr-reticulum
    restart: always
    command: bash -c "source ~/.bashrc; pushd assets; yarn; popd; mix deps.get; mix ecto.create; mix ecto.migrate; mix phx.server"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./reticulum:/ret
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  janus:
    build: janus
    image: yukimochi/mr-janus
    restart: always
    network_mode: "host"

  caddy:
    image: yukimochi/container-caddy
    restart: always
    network_mode: "host"
    volumes:
      - ./caddy/cert:/cert
      - ./caddy/conf:/etc/caddy
      - ./caddy/logs:/var/log/caddy
